#!/bin/bash

CODESOURCE=`dirname $0`
cd $CODESOURCE

source botfront
if [ $? -ne 0 ]; then exit; fi

sudo netstat -ant | grep -q 3306
# false
EXIT_CODE=$?
if [ $EXIT_CODE == 0 ]; then
exit
fi

# echo Opening tunnel to MySQL server
# ssh -N -y -L 3306:localhost:3306 $USER@$IP &

